#!/bin/sh

####################################
# Tear Down Ethernet bridge on Linux
####################################

eth="eth0"

# Define Bridge Interface
br="vpnbr0"

# Define list of TAP interfaces to be bridged together
tap="tap0 tap1 tap2"

# Correct default route
#gateway=$(ip route show default | awk '/default/ {print $3}')
#route add default gw $gateway $eth
#route del default gw $gateway $br

ifconfig $br down
brctl delbr $br

for t in $tap; do
    openvpn --rmtun --dev $t
done

