#!/bin/sh

#################################
# Set up Ethernet bridge on Linux
# Requires: bridge-utils
#################################

# Define Bridge Interface
br="vpnbr1"

# Define list of TAP interfaces to be bridged,
# for example tap="tap0 tap1 tap2".
tap="tap1"

# Define physical ethernet interface to be bridged
# with TAP interface(s) above.
#eth="eth0"
#eth_ip="10.10.1.2"
#eth_netmask="255.255.0.0"
#eth_broadcast="10.10.255.255"

# Grab current gateway
#gateway=$(ip route show default | awk '/default/ {print $3}')

for t in $tap; do
    openvpn --mktun --dev $t
done

#brctl addbr $br

for t in $tap; do
    brctl addif $br $t
done

for t in $tap; do
    ifconfig $t 0.0.0.0 promisc up
done

#ifconfig $br $eth_ip netmask $eth_netmask broadcast $eth_broadcast
#ifconfig $br up

# Correct default route
#route add default gw $gateway $br
#route del default gw $gateway $eth0
