#!/bin/sh

####################################
# Tear Down Ethernet bridge on Linux
####################################

# Define Bridge Interface
br="vpnbr0"

# Define list of TAP interfaces to be bridged together
tap="tap1"


#ifconfig $br down
#brctl delbr $br

for t in $tap; do
    openvpn --rmtun --dev $t
done

# Fix route
#eth_gateway="158.108.38.65"
#route add default gw $eth_gateway
